packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  '@ai-sdk/react': ^2.0.119
  '@better-auth/expo': 1.3.9
  '@eslint/eslintrc': ^3.3.3
  '@excalidraw/excalidraw': ^0.18.0
  '@ianvs/prettier-plugin-sort-imports': ^4.7.0
  '@tailwindcss/postcss': ^4.1.18
  '@tailwindcss/typography': ^0.5.19
  '@tanstack/query-async-storage-persister': ^5.90.18
  '@tanstack/form-core': ^1.27.7
  '@tanstack/react-form': ^1.27.7
  '@tanstack/react-query': ^5.90.16
  '@tanstack/react-query-persist-client': ^5.90.18
  '@tanstack/react-store': 0.7.5
  '@tauri-apps/api': ^2.9.1
  '@tauri-apps/plugin-deep-link': ^2.4.5
  '@tauri-apps/plugin-fs': ^2.4.4
  '@tauri-apps/plugin-http': ^2.5.4
  '@tauri-apps/plugin-opener': ^2.5.2
  '@tauri-apps/plugin-os': ^2.3.2
  '@tauri-apps/plugin-store': ^2.4.1
  '@tiptap/core': ^3.14.0
  '@tiptap/extension-code-block-lowlight': ^3.14.0
  '@tiptap/extension-color': ^3.14.0
  '@tiptap/extension-highlight': ^3.14.0
  '@tiptap/extension-mathematics': ^3.14.0
  '@tiptap/extension-placeholder': ^3.14.0
  '@tiptap/extension-text-align': ^3.14.0
  '@tiptap/extension-text-style': ^3.14.0
  '@tiptap/pm': ^3.14.0
  '@tiptap/react': ^3.14.0
  '@tiptap/starter-kit': ^3.14.0
  '@trpc/client': 11.6.0
  '@trpc/server': ^11.8.1
  '@trpc/tanstack-react-query': ^11.8.1
  '@types/node': ^22.19.3
  '@types/react': ~19.1.17
  '@types/react-dom': ~19.1.11
  ai: ^5.0.117
  babel-plugin-react-compiler: rc
  better-auth: 1.3.9
  class-variance-authority: 0.7.1
  dedent: ^1.7.1
  drizzle-orm: ^0.44.7
  eslint: ^9.39.2
  eslint-config-next: ^15.5.9
  globals: ^16.5.0
  katex: ^0.16.27
  lowlight: ^3.3.0
  lucide-react: ^0.544.0
  motion: ^12.23.26
  posthog-js: ^1.313.0
  posthog-node: ^5.18.1
  prettier: 3.6.2
  prettier-plugin-tailwindcss: ^0.6.14
  react: 19.1.0
  react-dom: 19.1.0
  react-router: ^7.11.0
  tailwind-merge: ^3.4.0
  tailwindcss: ^4.1.18
  typescript: ^5.9.3
  typescript-eslint: ^8.51.0
  zod: ^4.3.4

nodeLinker: hoisted

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - '@vercel/speed-insights'
  - core-js
  - core-js-pure
  - esbuild
  - sharp
  - unrs-resolver
