packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  react: ^19.1.0
  react-dom: ^19.1.0
  eslint: ^9.27.0
  prettier: ^3.5.3
  tailwindcss: ^4.1.8
  typescript: ^5.8.3
  zod: ^4.0.0
  '@tanstack/react-query': ^5.76.1
  '@tanstack/react-form': ^1.11.2
  '@trpc/client': ^11.1.2
  '@trpc/server': ^11.1.2
  '@trpc/tanstack-react-query': ^11.1.2
  class-variance-authority: ^0.7.1
  tailwind-merge: ^3.3.0
  '@types/react': ^19.1.4
  '@types/react-dom': ^19.1.5
  '@types/node': ^22.15.19
  '@tailwindcss/postcss': ^4.1.7
  '@tailwindcss/typography': ^0.5.16
  '@ianvs/prettier-plugin-sort-imports': ^4.4.1
  prettier-plugin-tailwindcss: ^0.6.11
  react-router: ^7.6.1
  '@tanstack/query-async-storage-persister': ^5.79.0
  '@tanstack/react-query-persist-client': ^5.79.0
  better-auth: ^1.2.8
  '@daveyplate/better-auth-tanstack': ^1.3.6
  posthog-js: ^1.249.3
  posthog-node: ^5.0.0
  '@radix-ui/react-icons': ^1.3.2
  drizzle-orm: ^0.43.1
  '@tiptap/react': ^3.0.6
  '@tauri-apps/api': ^2.5.0
  '@tauri-apps/plugin-deep-link': ^2.3.0
  '@tauri-apps/plugin-opener': ^2.3.0
  '@tauri-apps/plugin-fs': ^2.3.0
  '@tauri-apps/plugin-http': ^2.4.4
  '@tauri-apps/plugin-os': ^2.2.2
  '@tauri-apps/plugin-store': ^2.2.1

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - '@vercel/speed-insights'
  - core-js
  - esbuild
  - sharp
  - unrs-resolver
