packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  '@ai-sdk/react': ^2.0.41
  '@better-auth/expo': 1.3.9
  '@eslint/eslintrc': ^3.3.1
  '@ianvs/prettier-plugin-sort-imports': ^4.7.0
  '@tailwindcss/postcss': ^4.1.13
  '@tailwindcss/typography': ^0.5.16
  '@tanstack/query-async-storage-persister': ^5.87.4
  '@tanstack/react-form': ^1.19.5
  '@tanstack/react-query': ^5.87.4
  '@tanstack/react-query-persist-client': ^5.87.4
  '@tanstack/react-store': 0.7.5
  '@tauri-apps/api': ^2.8.0
  '@tauri-apps/plugin-deep-link': ^2.4.3
  '@tauri-apps/plugin-fs': ^2.4.2
  '@tauri-apps/plugin-http': ^2.5.2
  '@tauri-apps/plugin-opener': ^2.5.0
  '@tauri-apps/plugin-os': ^2.3.1
  '@tauri-apps/plugin-store': ^2.4.0
  '@tiptap/core': ^3.4.2
  '@tiptap/react': ^3.4.2
  '@tiptap/starter-kit': ^3.4.2
  '@tiptap/pm': ^3.4.2
  '@tiptap/extension-code-block-lowlight': ^3.4.2
  '@tiptap/extension-color': ^3.4.2
  '@tiptap/extension-highlight': ^3.4.2
  '@tiptap/extension-mathematics': ^3.4.2
  '@tiptap/extension-placeholder': ^3.4.2
  '@tiptap/extension-text-align': ^3.4.2
  '@tiptap/extension-text-style': ^3.4.2
  '@trpc/client': ^11.5.1
  '@trpc/server': ^11.5.1
  '@trpc/tanstack-react-query': ^11.5.1
  '@types/node': ^22.18.1
  '@types/react': ~19.1.12
  '@types/react-dom': ~19.1.9
  ai: ^5.0.41
  babel-plugin-react-compiler: rc
  better-auth: 1.3.9
  class-variance-authority: 0.7.1
  dedent: ^1.7.0
  drizzle-orm: ^0.44.5
  eslint: ^9.35.0
  eslint-config-next: ^15.5.3
  globals: ^16.4.0
  katex: ^0.16.22
  lowlight: ^3.3.0
  lucide-react: ^0.540.0
  motion: ^12.23.12
  posthog-js: ^1.264.2
  posthog-node: ^5.8.4
  prettier: 3.6.2
  prettier-plugin-tailwindcss: ^0.6.14
  react: ^19.1.1
  react-dom: ^19.1.1
  react-router: ^7.8.2
  tailwind-merge: ^3.3.1
  tailwindcss: ^4.1.13
  typescript: ^5.9.2
  typescript-eslint: ^8.43.0
  zod: ^4.1.8

nodeLinker: hoisted

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - '@vercel/speed-insights'
  - core-js
  - core-js-pure
  - esbuild
  - sharp
  - unrs-resolver
