packages:
  - "apps/**"
  - "packages/**"
  - "tooling/**"

catalog:
  react: ^19.1.1
  react-dom: ^19.1.1
  eslint: ^9.32.0
  prettier: ^3.6.2
  tailwindcss: ^4.1.11
  typescript: ^5.9.2
  zod: ^4.0.14
  "@tanstack/react-query": ^5.84.1
  "@tanstack/react-form": ^1.15.2
  "@trpc/client": ^11.4.3
  "@trpc/server": ^11.4.3
  "@trpc/tanstack-react-query": ^11.4.3
  class-variance-authority: ^0.7.1
  tailwind-merge: ^3.3.1
  "@types/react": ^19.1.9
  "@types/react-dom": ^19.1.7
  "@types/node": ^22.17.0
  "@tailwindcss/postcss": ^4.1.11
  "@tailwindcss/typography": ^0.5.16
  "@ianvs/prettier-plugin-sort-imports": ^4.5.1
  prettier-plugin-tailwindcss: ^0.6.14
  react-router: ^7.7.1
  "@tanstack/query-async-storage-persister": ^5.83.1
  "@tanstack/react-query-persist-client": ^5.84.1
  better-auth: ^1.3.4
  posthog-js: ^1.258.5
  posthog-node: ^5.6.0
  "@radix-ui/react-icons": ^1.3.2
  drizzle-orm: ^0.44.4
  "@tiptap/react": ^3.0.9
  "@tauri-apps/api": ^2.7.0
  "@tauri-apps/plugin-deep-link": ^2.4.1
  "@tauri-apps/plugin-opener": ^2.4.0
  "@tauri-apps/plugin-fs": ^2.4.1
  "@tauri-apps/plugin-http": ^2.5.1
  "@tauri-apps/plugin-os": ^2.3.0
  "@tauri-apps/plugin-store": ^2.3.0

onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - "@vercel/speed-insights"
  - core-js
  - esbuild
  - sharp
  - unrs-resolver
