packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  '@ai-sdk/react': ^2.0.56
  '@better-auth/expo': 1.3.9
  '@eslint/eslintrc': ^3.3.1
  '@excalidraw/excalidraw': ^0.18.0
  '@ianvs/prettier-plugin-sort-imports': ^4.7.0
  '@tailwindcss/postcss': ^4.1.13
  '@tailwindcss/typography': ^0.5.19
  '@tanstack/query-async-storage-persister': ^5.90.2
  '@tanstack/form-core': ^1.24.0
  '@tanstack/react-form': ^1.23.4
  '@tanstack/react-query': ^5.90.2
  '@tanstack/react-query-persist-client': ^5.90.2
  '@tanstack/react-store': 0.7.5
  '@tauri-apps/api': ^2.8.0
  '@tauri-apps/plugin-deep-link': ^2.4.3
  '@tauri-apps/plugin-fs': ^2.4.2
  '@tauri-apps/plugin-http': ^2.5.2
  '@tauri-apps/plugin-opener': ^2.5.0
  '@tauri-apps/plugin-os': ^2.3.1
  '@tauri-apps/plugin-store': ^2.4.0
  '@tiptap/core': ^3.6.1
  '@tiptap/extension-code-block-lowlight': ^3.6.1
  '@tiptap/extension-color': ^3.6.1
  '@tiptap/extension-highlight': ^3.6.1
  '@tiptap/extension-mathematics': ^3.6.1
  '@tiptap/extension-placeholder': ^3.6.1
  '@tiptap/extension-text-align': ^3.6.1
  '@tiptap/extension-text-style': ^3.6.1
  '@tiptap/pm': ^3.6.1
  '@tiptap/react': ^3.6.1
  '@tiptap/starter-kit': ^3.6.1
  '@trpc/client': 11.6.0
  '@trpc/server': ^11.6.0
  '@trpc/tanstack-react-query': ^11.6.0
  '@types/node': ^22.18.6
  '@types/react': ~19.1.14
  '@types/react-dom': ~19.1.9
  ai: ^5.0.56
  babel-plugin-react-compiler: rc
  better-auth: 1.3.9
  class-variance-authority: 0.7.1
  dedent: ^1.7.0
  drizzle-orm: ^0.44.5
  eslint: ^9.36.0
  eslint-config-next: ^15.5.4
  globals: ^16.4.0
  katex: ^0.16.22
  lowlight: ^3.3.0
  lucide-react: ^0.544.0
  motion: ^12.23.22
  posthog-js: ^1.268.6
  posthog-node: ^5.9.1
  prettier: 3.6.2
  prettier-plugin-tailwindcss: ^0.6.14
  react: 19.1.0
  react-dom: 19.1.0
  react-router: ^7.9.3
  tailwind-merge: ^3.3.1
  tailwindcss: ^4.1.13
  typescript: ^5.9.2
  typescript-eslint: ^8.44.1
  zod: ^4.1.11

nodeLinker: hoisted

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - '@vercel/speed-insights'
  - core-js
  - core-js-pure
  - esbuild
  - sharp
  - unrs-resolver
