packages:
  - apps/**
  - packages/**
  - tooling/**

catalog:
  '@ai-sdk/react': ^2.0.28
  '@eslint/eslintrc': ^3.3.1
  '@ianvs/prettier-plugin-sort-imports': ^4.7.0
  '@tailwindcss/postcss': ^4.1.12
  '@tanstack/query-async-storage-persister': ^5.85.6
  '@tanstack/react-form': 1.14.2
  '@tanstack/react-query': ^5.85.6
  '@tanstack/react-query-persist-client': ^5.85.6
  '@tanstack/react-store': 0.7.3
  '@tauri-apps/api': ^2.8.0
  '@tauri-apps/plugin-deep-link': ^2.4.2
  '@tauri-apps/plugin-fs': ^2.4.2
  '@tauri-apps/plugin-http': ^2.5.2
  '@tauri-apps/plugin-opener': ^2.5.0
  '@tauri-apps/plugin-os': ^2.3.1
  '@tauri-apps/plugin-store': ^2.4.0
  '@tiptap/core': ^3.3.0
  '@tiptap/react': ^3.3.0
  '@trpc/client': ^11.5.0
  '@trpc/server': ^11.5.0
  '@trpc/tanstack-react-query': ^11.5.0
  '@types/node': 22.17.0
  '@types/react': 19.1.9
  '@types/react-dom': ^19.1.9
  ai: 5.0.8
  babel-plugin-react-compiler: rc
  better-auth: ^1.3.7
  class-variance-authority: ^0.7.1
  dedent: ^1.6.0
  drizzle-orm: ^0.44.5
  eslint: ^9.34.0
  eslint-config-next: ^15.5.2
  globals: ^16.3.0
  lucide-react: 0.540.0
  motion: ^12.23.12
  posthog-js: ^1.261.0
  posthog-node: ^5.8.1
  prettier: ^3.6.2
  prettier-plugin-tailwindcss: ^0.6.14
  react: 19.1.1
  react-dom: ^19.1.1
  react-router: ^7.8.2
  tailwind-merge: ^3.3.1
  tailwindcss: ^4.1.12
  typescript: ^5.9.2
  typescript-eslint: ^8.41.0
  zod: 4.0.14

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - '@vercel/speed-insights'
  - core-js
  - esbuild
  - sharp
  - unrs-resolver
