packages:
  - apps/**
  - packages/**
  - tooling/**

catalog:
  '@ianvs/prettier-plugin-sort-imports': ^4.5.1
  '@radix-ui/react-icons': ^1.3.2
  '@tailwindcss/postcss': ^4.1.11
  '@tailwindcss/typography': ^0.5.16
  '@tanstack/query-async-storage-persister': ^5.83.1
  '@tanstack/react-form': 1.14.2
  '@tanstack/react-query': ^5.84.1
  '@tanstack/react-query-persist-client': ^5.84.1
  '@tauri-apps/api': ^2.7.0
  '@tauri-apps/plugin-deep-link': ^2.4.1
  '@tauri-apps/plugin-fs': ^2.4.1
  '@tauri-apps/plugin-http': ^2.5.1
  '@tauri-apps/plugin-opener': ^2.4.0
  '@tauri-apps/plugin-os': ^2.3.0
  '@tauri-apps/plugin-store': ^2.3.0
  '@tiptap/react': ^3.0.9
  '@trpc/client': ^11.4.3
  '@trpc/server': ^11.4.3
  '@trpc/tanstack-react-query': ^11.4.3
  '@types/node': 22.17.0
  '@types/react': ^19.1.9
  '@types/react-dom': ^19.1.7
  babel-plugin-react-compiler: rc
  better-auth: ^1.3.4
  class-variance-authority: ^0.7.1
  drizzle-orm: ^0.44.4
  eslint: ^9.32.0
  posthog-js: ^1.258.5
  posthog-node: ^5.6.0
  prettier: ^3.6.2
  prettier-plugin-tailwindcss: ^0.6.14
  react: ^19.1.1
  react-dom: ^19.1.1
  react-router: ^7.7.1
  tailwind-merge: ^3.3.1
  tailwindcss: ^4.1.11
  typescript: ^5.9.2
  zod: ^4.0.14

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - '@vercel/speed-insights'
  - core-js
  - esbuild
  - sharp
  - unrs-resolver
