packages:
  - apps/**
  - packages/**
  - tooling/**

catalog:
  '@ai-sdk/react': ^2.0.8
  '@eslint/eslintrc': ^3.3.1
  '@ianvs/prettier-plugin-sort-imports': ^4.6.1
  '@tailwindcss/postcss': ^4.1.11
  '@tanstack/query-async-storage-persister': ^5.83.1
  '@tanstack/react-form': 1.14.2
  '@tanstack/react-query': ^5.84.2
  '@tanstack/react-query-persist-client': ^5.84.2
  '@tauri-apps/api': ^2.7.0
  '@tauri-apps/plugin-deep-link': ^2.4.1
  '@tauri-apps/plugin-fs': ^2.4.1
  '@tauri-apps/plugin-http': ^2.5.1
  '@tauri-apps/plugin-opener': ^2.4.0
  '@tauri-apps/plugin-os': ^2.3.0
  '@tauri-apps/plugin-store': ^2.3.0
  '@tiptap/core': ^3.0.9
  '@tiptap/react': ^3.0.9
  '@trpc/client': ^11.4.4
  '@trpc/server': ^11.4.4
  '@trpc/tanstack-react-query': ^11.4.4
  '@types/node': 22.17.0
  '@types/react': 19.1.9
  '@types/react-dom': ^19.1.7
  ai: 5.0.8
  babel-plugin-react-compiler: rc
  better-auth: ^1.3.4
  class-variance-authority: ^0.7.1
  dedent: ^1.6.0
  drizzle-orm: ^0.44.4
  eslint: ^9.33.0
  eslint-config-next: ^15.4.6
  globals: ^16.3.0
  lucide-react: 0.540.0
  motion: ^12.23.12
  posthog-js: ^1.259.0
  posthog-node: ^5.6.0
  prettier: ^3.6.2
  prettier-plugin-tailwindcss: ^0.6.14
  react: 19.1.1
  react-dom: ^19.1.1
  react-router: ^7.8.0
  tailwind-merge: ^3.3.1
  tailwindcss: ^4.1.11
  typescript: ^5.9.2
  typescript-eslint: ^8.39.0
  zod: 4.0.14

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - '@vercel/speed-insights'
  - core-js
  - esbuild
  - sharp
  - unrs-resolver
