on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install dependencies
        run: npm install -g bun && bun install

      - name: Format
        run: bunx turbo format
      
      - name: Typecheck
        run: bunx turbo typecheck

      - name: Lint
        run: bunx turbo lint